### ISSUE TITLE
Need some method to contact

### ISSUE THREAD

**Issue by Rousan99** [pdcxs/ManimProjects#1]
Hi, I have seen your physics simulator. Can you explain it to me more😅...some Syntax?

**Comment by pdcxs** [comment]
It's just a very simple wrap of the pymunk physics engine. You can first study how to use pymunk, read the official document or watch some video tutorials on youtube. Then you can see the [physics branch](https://github.com/pdcxs/manim/tree/physics). The example_scenes.py in the physics branch shows how to use the new scene and mobjects.
